name: Telegram Post Scheduler

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DEEPSEEK_APPI: ${{ secrets.DEEPSEEK_APPI }}
      USERNAMETELERGRAMBOT: ${{ secrets.USERNAMETELERGRAMBOT }}
      TELEGRAMKEY: ${{ secrets.TELEGRAMKEY }}
      TELEGRAMKANAL: ${{ secrets.TELEGRAMKANAL }}
      TGUSERID: ${{ secrets.TGUSERID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Black (check)
        run: black --check .

      - name: Ruff
        run: ruff .

      - name: Run telegram post once
        run: python -m src.telegram_post.main poll-once
